from enum import Enum


class GCodeSection(str, Enum):
    TOP_COMMENT_SECTION = "TOP_COMMENT"
    STARTUP_SCRIPT_SECTION = "STARTUP_SCRIPT"
    GCODE_MOVEMENTS_SECTION = "GCODE_MOVEMENTS"
    END_SCRIPT_SECTION = "END_SCRIPT"
    BOTTOM_COMMENT = "BOTTOM_COMMENT"
